FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/staticfiles

EXPOSE 8000

CMD sh -c "echo 'Waiting for DB...' && \
while ! nc -z $POSTGRES_HOST 5432; do sleep 1; done && \
python manage.py migrate --noinput && \
python manage.py collectstatic --noinput && \
gunicorn seekClarity_backend.wsgi:application \
--bind 0.0.0.0:8000 \
--timeout 120 \
--workers 2"